import { useMemo, useState, useEffect } from "react";
import ColumnSelector from "./components/ColumnSelector";
import PipelineRunner from "./components/PipelineRunner";
import ResultsDashboard from "./components/ResultsDashboard";
import UploadPanel from "./components/UploadPanel";
import { getResults, initContract, runPipeline, selectBias, uploadFile } from "./services/api";

const steps = [
  { 
    label: "Upload Dataset", 
    desc: "Provide your raw CSV data file containing the historical records. This dataset serves as the foundation for the analysis. Make sure the file includes both feature columns and the target outcome.",
    icon: <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" /></svg>
  },
  { 
    label: "Select Target + Bias", 
    desc: "Choose the specific column you want the model to predict. Then, identify the sensitive attribute (such as age, gender, or race) that you want to evaluate for potential bias.",
    icon: <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" /></svg>
  },
  { 
    label: "Run Full Pipeline", 
    desc: "Execute the end-to-end machine learning pipeline. This automatically handles data preprocessing, trains an optimized fairness-aware classifier, and evaluates its performance.",
    icon: <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M5.25 5.653c0-.856.917-1.398 1.667-.986l11.54 6.348a1.125 1.125 0 010 1.971l-11.54 6.347a1.125 1.125 0 01-1.667-.985V5.653z" /></svg>
  },
  { 
    label: "View Decision Dashboard", 
    desc: "Analyze the final outcomes generated by the model. Review the comprehensive fairness metrics, predictive accuracy, and feature importance to ensure compliance.",
    icon: <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" /></svg>
  },
];

const LOADING_MESSAGES = [
  "Initializing AI Pipeline...",
  "Analyzing Feature Distributions...",
  "Identifying Bias Patterns...",
  "Optimizing Fairness Constraints...",
  "Applying Mitigation Algorithms...",
  "Generating Compliance Reports...",
  "Finalizing Decision Dashboard...",
  "Preparing Insight Visualizations..."
];

function formatApiError(err, fallbackMessage) {
  const detail = err?.response?.data?.detail;
  const message = typeof detail === "string" ? detail : "";

  if (message.includes("Encoders require their input argument must be uniformly strings or numbers")) {
    return "Data preprocessing failed because one or more columns contain mixed value types. Please normalize those columns in the CSV and try again.";
  }

  return message || fallbackMessage;
}

function App() {
  const [step, setStep] = useState(0);
  const [file, setFile] = useState(null);
  const [uploadData, setUploadData] = useState(null);
  const [contract, setContract] = useState(null);
  const [targetColumn, setTargetColumn] = useState("");
  const [selectedBias, setSelectedBias] = useState([]);
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [loadingMsg, setLoadingMsg] = useState(LOADING_MESSAGES[0]);

  // Continuously change loading text
  useEffect(() => {
    let interval;
    if (loading) {
      let index = 0;
      interval = setInterval(() => {
        index = (index + 1) % LOADING_MESSAGES.length;
        setLoadingMsg(LOADING_MESSAGES[index]);
      }, 2000);
    }
    return () => clearInterval(interval);
  }, [loading]);

  const resetAll = () => {
    setStep(0);
    setFile(null);
    setUploadData(null);
    setContract(null);
    setTargetColumn("");
    setSelectedBias([]);
    setResults(null);
    setError("");
    setLoadingMsg(LOADING_MESSAGES[0]);
  };

  const selectableColumns = useMemo(() => {
    if (uploadData?.columns?.length) return uploadData.columns;
    if (!contract?.X?.length) return [];
    return Object.keys(contract.X[0]);
  }, [contract, uploadData]);

  const onUpload = async () => {
    if (!file) {
      setError("Please choose a CSV file.");
      return;
    }
    setLoading(true);
    setError("");
    try {
      const data = await uploadFile(file);
      setUploadData(data);
      
      // Default to "Survived" if it exists, otherwise use last column
      const defaultTarget = data.columns?.find(c => c.toLowerCase() === "survived") 
        || data.columns?.[data.columns.length - 1] 
        || "";
      
      setTargetColumn(defaultTarget);
      
      // Auto-initialize contract
      const contractData = await initContract(defaultTarget);
      setContract(contractData);
      
      // Auto-select empty bias initially
      const biasData = await selectBias([]);
      setContract((prev) => ({ ...prev, ...biasData }));
      
      setStep(1);
    } catch (err) {
      setError(formatApiError(err, "Upload failed."));
    } finally {
      setLoading(false);
    }
  };

  const handleTargetChange = async (col) => {
    setTargetColumn(col);
    if (!col) return;
    setLoading(true);
    try {
      const data = await initContract(col);
      setContract(data);
      // Reset bias when target changes as the options change
      const biasData = await selectBias([]);
      setContract((prev) => ({ ...prev, ...biasData }));
      setSelectedBias([]);
    } catch (err) {
      setError(formatApiError(err, "Contract update failed."));
    } finally {
      setLoading(false);
    }
  };

  const handleBiasChange = async (biasCols) => {
    setSelectedBias(biasCols);
    setLoading(true);
    try {
      const data = await selectBias(biasCols);
      setContract((prev) => ({ ...prev, ...data }));
    } catch (err) {
      setError(formatApiError(err, "Bias update failed."));
    } finally {
      setLoading(false);
    }
  };

  const onRunPipeline = async () => {
    setLoading(true);
    setError("");
    const startTime = Date.now();
    try {
      await runPipeline();
      const data = await getResults();
      
      // Ensure at least 3s for the dynamic text to cycle
      const elapsed = Date.now() - startTime;
      if (elapsed < 3000) {
        await new Promise(r => setTimeout(r, 3000 - elapsed));
      }
      
      setResults(data);
      setStep(3);
    } catch (err) {
      setError(formatApiError(err, "Pipeline run failed."));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="page">
      <header className="topbar">
        <div className="brand">Bias Platform</div>
        <nav className="topnav">
          <input type="search" className="search-input" placeholder="Search..." />
          <a href="#home">Home</a>
          <a href="#pipeline">Pipeline</a>
          <a href="#results">Results</a>
        </nav>
        <button className="btn-new-run" onClick={resetAll}>New Run</button>
      </header>

      <main className="container" id="home">
        <section className="hero">
          <div className="floating-shape shape-1"></div>
          <div className="floating-shape shape-2"></div>
          <div className="floating-shape shape-3"></div>
          <div className="floating-shape shape-4"></div>
          <h1>Decision Intelligence Dashboard</h1>
          <p className="lead">
            Upload data, run fairness-aware inference, and inspect decision, validation, and monitoring outputs.
          </p>
        </section>

        <section id="pipeline">
          <h2>Pipeline Progress</h2>
          <div className="stepper-wrapper">
            <div className="stepper">
              {steps.map((s, idx) => (
                <div key={s.label} className={`step ${step >= idx ? "active" : ""}`}>
                  <div className="step-header">
                    <div className="step-icon">{s.icon}</div>
                    <div className="step-number">{idx + 1}</div>
                  </div>
                  <p className="step-title">{s.label}</p>
                  <div className="step-desc-wrapper">
                    <div className="step-desc">{s.desc}</div>
                  </div>
                </div>
              ))}
            </div>
            <div className="timeline-wave-container">
              <div 
                className="timeline-wave-fill" 
                style={{ width: `${step === 0 ? 15 : (step / (steps.length - 1)) * 100}%` }}
              ></div>
            </div>
          </div>
        </section>

        <UploadPanel file={file} loading={loading} onFileChange={setFile} onUpload={onUpload} />

        {uploadData && (
          <ColumnSelector
            columns={selectableColumns}
            targetColumn={targetColumn}
            selectedBias={selectedBias}
            loading={loading}
            onTargetChange={handleTargetChange}
            onBiasChange={handleBiasChange}
          />
        )}

        {contract && <PipelineRunner loading={loading} hasResults={Boolean(results)} onRunPipeline={onRunPipeline} />}

        {results && <ResultsDashboard results={results} />}

        {error && <p className="error">{error}</p>}
      </main>

      {loading && (
        <div className="loading-overlay">
          <div className="spinner-container">
            <div className="modern-spinner">
              <div className="neural-node"></div>
              <div className="neural-node"></div>
              <div className="neural-node"></div>
            </div>
            <p className="loading-text">{loadingMsg}</p>
          </div>
        </div>
      )}

      <footer className="footer">
        <div className="footer-bottom">
          <p>&copy; {new Date().getFullYear()} Bias Platform Inc. All rights reserved.</p>
          <div className="social-links">
            <a href="#twitter">Twitter</a>
            <a href="#github">GitHub</a>
            <a href="#linkedin">LinkedIn</a>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;